language: python

python: 2.7

os:
  - linux

env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34

matrix:
  include:
    - python: 3.5
      env: TOX_ENV=py35
    - python: 3.6
      env: TOX_ENV=py36

install:
  - pip install tox

script:
    - tox -e $TOX_ENV
